spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/planets
    password: changeme
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: none
    show-sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081